features = [
    "fiscal_register",
    "barcode_from_xml",
    "scales_from_xml",
    "drawer_close",
]

[type]
id = "touch"
name = "Touch POS"
aliases = ["touch"]
icon = "pos"
os_hints = ["ubuntu"]

[connection.db]
enabled = false

